### ISSUE TITLE
Java example for the implementation

### ISSUE THREAD

**Issue by ilyassesalama** [dotlottie/dotlottieloader-android#3]
It'd be very nice to provide a Java example of this cool library.

**Comment by ilyassesalama** [comment]
It seems like `.lottie` animations work with the Lottie library without importing DotLottie library by using it directly in XML or programmatically.
Cool, better than messing around to import a Kotlin library in a Java project even though I figured out how to use it in Java.

XML:
```
 <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animationView"
            android:layout_width="match_parent"
            app:lottie_fileName="animation_relaxing.lottie"
            android:layout_height="200dp"
            app:lottie_autoPlay="true"
            android:scaleType="centerCrop"
            app:lottie_loop="true" />
```

Programmatically:
```
binding.animationView.setAnimation("animation.lottie");
binding.animationView.playAnimation();
```

I wonder what this library adds if it just works with the original library. DotLottie animations are the best IMO.

**Comment by sandeepyohans** [comment]
Hi, want to share one observation here. My animation file (json) size is 181KB but when I converted it to dotLottie it was reduced to 41KB. So the app size can be brought down using dotLottie.

**Comment by ilyassesalama** [comment]
Uh, that's literally the main advantage of this entire new standard.
